icons_format = "{icon}"

[theme]
theme = "dracula"

[theme.overrides]
idle_bg = "#123456"

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection}"
format_alt = "$device"

[[block]]
block = "cpu"
# Add memory usage information here
format = " $icon $utilization"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2)"
format_alt = " RAM: $mem_used GB / $mem_total GB"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "MB"
interval = 0.1
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2)"

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume|}"

[[block]]
block = "battery"
format = " $icon {$percentage} {$time}"

[[block]]
block = "time"
interval = 3
format = " $icon $timestamp.datetime(f:'%a %m/%d %I:%M %p')"

